### ISSUE TITLE
"Modern" build system for py3

### ISSUE THREAD

**Issue by Amar1729** [pyroscope/pyrocore#102]
Would there be any interest from the maintainers in moving to a "modern" dependency management/build systems such as [poetry](https://python-poetry.org/) or [pybuilder](https://pybuilder.io/)?

`pybuilder` is a somewhat well-known build automation tool for python (honestly it seems pretty similar to paver), whereas poetry is meant primarily for stronger dependency handling than pip by itself (specifically poetry uses the new-ish Pipfile.lock, to give you deterministic builds)

I know python3 support is still a work in progress and there's active development in parts of the project aside from just the tooling required from the upgrade, so I understand this might be an idea that isn't really looked at as helpful/good use of time.

If there's some interest I can put in some work to clean up the bash scripts/pavement.py in a more concise way - this is an initial take on what a `pyproject.toml` from poetry for `pyrocore` would look like:

```toml
[tool.poetry]
name = "pyrocore"
version = "0.5.3"
description = "PyroCore - Python Torrent Tools Core Package."
authors = ["The PyroScope Project <pyroscope.project@gmail.com>"]
license = "GPL-2.0"

[tool.poetry.dependencies]
python = "^3.6"
requests = "<3,>=2.1.0"
prompt-toolkit = "<2,>=1.0.14"
tempita = ">=0.5.1"
pyrobase = {git = "https://github.com/pyroscope/pyrobase.git"}

[tool.poetry.dev-dependencies]
coverage = "^5.1"
nose = "^1.3.7"
paver = "^1.3.4"
pylint = "^2.5.0"
bpython = "^0.19"
pip-upgrader = "^1.4.15"
sphinx = "^3.0.3"
apscheduler = "^3.6.3"
waitress = "^1.4.3"
webob = "^1.8.6"
psutil = "^5.7.0"
twine = "^3.1.1"  # requires python ^3.6

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
chtor = "pyrocore.scripts.chtor:run"
hashcheck = "pyrocore.scripts.hashcheck:run"
lstor = "pyrocore.scripts.lstor:run"
mktor = "pyrocore.scripts.mktor:run"
pyroadmin = "pyrocore.scripts.pyroadmin:run"
rtcontrol = "pyrocore.scripts.rtcontrol:run"
rtevent = "pyrocore.scripts.rtevent:run"
rtmv = "pyrocore.scripts.rtmv:run"
rtsweep = "pyrocore.scripts.rtsweep:run"
rtxmlrpc = "pyrocore.scripts.rtxmlrpc:run"
pyrotorque = "pyrocore.scripts.pyrotorque:run"

```

Pros:
- standardized systems (others can more easily help with dev)
- poetry gives a more concise way of describing deps - described in sections such as direct or dev, (similar to the convention of using requirements.txt and requirements-dev.txt) but all in one place. can be installed with `poetry install` or `poetry install --dev`, respectively
  - attempts to fix the issue of relying on old versions of pkgs that `pip list` runs into
- pybuilder could help remove lots of the current bash scripts/pavement that are helping with dependency mgmt/building

Cons:
- takes time/effort/testing to switchover
- learning curve for anyone not familiar
- current build system development (e.g. paver, update-head.sh) feel like sunk costs since they're fairly complex+complete
